# Keep all in alphabetical order
components:
  crates/env-var:
    - jbovet
    - MatteoJoliveau
  crates/flagd:
    - erenatas
    - sheepduke
  crates/flipt:
    - tamaroning
  crates/ofrep:
    - erenatas
    - Rahul-Baradol
  crates/flagsmith:
    - matthewelwell
    - zaimwa9

ignored-authors:
  - renovate-bot
